- name: Setup new fedora 31 machine
  hosts: all
  tasks:

  #  - name: Update all packages
  #    dnf:
  #      name: '*'
  #      state: latest

  #  - name: Install RPM Fusion Free repository
  #    dnf:
  #      name: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-31.noarch.rpm
  #      state: present

  #  - name: Install RPM Fusion Non Free repository
  #    dnf:
  #      name: http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-31.noarch.rpm
  #      state: present

    - name: Install required packages
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - digikam
          - gimp
          - sysstat
          - vlc
          - keepassx
          - java-1.8.0-openjdk-devel
          - lm_sensors
          - gnome-shell-extension-pomodoro
          - gnome-tweaks
          - xclip
          - chromium
          - podman-compose

  #  - name: Remove docker old versions
  #    dnf:
  #      name: "{{ packages }}"
  #      state: absent
  #      autoremove: yes
  #    vars:
  #      packages:
  #        - docker
  #        - docker-client
  #        - docker-client-latest
  #        - docker-common
  #        - docker-latest
  #        - docker-latest-logrotate
  #        - docker-logrotate
  #        - docker-selinux
  #        - docker-engine-selinux
  #        - docker-engine

  #  - name: Install Fedora Workstation repository
  #    dnf:
  #      name: fedora-workstation-repositories
  #      state: present
      
  #  - name: Enable Chrome repository
  #    shell: dnf config-manager --set-enabled google-chrome

  #  - name: Install Chrome
  #    dnf:
  #      name: google-chrome-stable
  #      state: present

  #  - name: Create Home bin dir
  #    file:
  #      path: /home/jorge/bin
  #      state: directory

  #  - name: Create SoapUI home dir
  #    file:
  #      path: /opt/soapui
  #      state: directory

  #  - name: Unpack SoapUI
  #    unarchive:
  #      src: files/SoapUI-5.5.0-linux-bin.tar.gz
  #      dest: /opt/soapui
  #      owner: jorge 
  #      group: jorge
    
  #  - name: Create SoapUI symbolic link 
  #    file:
  #      src: "/opt/soapui/SoapUI-5.5.0/bin/soapui.sh"
  #      dest: "/home/jorge/bin/soapui.sh"
  #      state: link
    
  #  - name: Import VSC key
  #    rpm_key:
  #      state: present
  #      key: https://packages.microsoft.com/keys/microsoft.asc

  #  - name: Create VSC repo
  #    yum_repository:
  #      name: code
  #      description: Visual Studio Code
  #      baseurl: https://packages.microsoft.com/yumrepos/vscode
  #      gpgcheck: yes
  #      gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  #  - name: Install VSC
  #    dnf:
  #      name: code
  #      state: present

  #  - name: Create Projects dir
  #    file:
  #      path: /home/jorge/Projects
  #      state: directory
  #      owner: jorge
  #      group: jorge

