- name: Setup new fedora 40 machine
  hosts: localhost
  become: true
  tasks:

#  - name: Set hostname
#    hostname:
#      name: jaxps.sevolutivo.ec
#
#  - name: Update all packages
#    dnf:
#      name: '*'
#      state: latest
#
#  - name: Import RPM Fusion Free repository key
#    ansible.builtin.rpm_key:
#      state: present
#      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
#
#  - name: Install RPM Fusion Free repository
#    dnf:
#      name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-40.noarch.rpm
#      state: present
#
#  - name: Import RPM Fusion Free repository key
#    ansible.builtin.rpm_key:
#      state: present
#      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
#
#  - name: Install RPM Fusion Non Free repository
#    dnf:
#      name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-40.noarch.rpm
#      state: present
#
#  - name: Install required packages
#    dnf:
#      name: "{{ packages }}"
#      state: latest
#    vars:
#      packages:
#        - digikam
#        - darktable
#        - gimp
#        - sysstat
#        - java-1.8.0-openjdk-devel
#        - lm_sensors
#        - gnome-shell-extension-pomodoro
#        - gnome-tweaks
#        - xclip
#        - chromium
#        - podman-docker
#        - podman-compose
#        - podman-remote
#        - nmap
#        - httpie
#        - virt-manager
#        - libvirt-client
#        - vlc
#        - ffmpeg-free
#        - libavcodec-freeworld
#        - fuse-exfat
#        - exfat-utils
#        - git-extras
#        - hdparm
#        - fzf
#        - neofetch
#        - bat
#        - gnome-extensions-app
#        - java-11-openjdk-devel
#        - java-17-openjdk-devel
#
#  - name: Install Chrome
#    dnf:
#      name: google-chrome-stable
#      state: present
#
#  - name: Remove nano as defualt editor
#    dnf:
#      name: nano-default-editor
#      state: absent
#  
#  - name: Create SoapUI home dir
#    file:
#      path: /opt/soapui
#      state: directory
#      owner: jorge
#      group: jorge  
#
#  - name: Find SoapUI tar file
#    find:
#      paths: files
#      patterns: SoapUI-5.*-linux-bin.tar.gz 
#    register: soapui
#
#  - name: Unpack SoapUI
#    unarchive:
#      src: "{{ item.path }}"
#      dest: /opt/soapui
#      owner: jorge
#      group: jorge
#    with_items: "{{ soapui.files }}"
#  
#  - name: Find SoapUI directory
#    find:
#      paths: /opt/soapui
#      patterns: 'SoapUI-5.*'
#      file_type: directory
#    register: soapui_dir
#
#  - name: Create SoapUI symbolic link 
#    file:
#      src: "{{item.path}}/bin/soapui.sh"
#      dest: "/usr/local/bin/soapui.sh"
#      state: link
#    with_items: "{{ soapui_dir.files }}"
#  
#  - name: Install JHipster generator
#    npm:
#      name: generator-jhipster
#      global: yes
#
#  - name: Install yo
#    npm:
#      name: yo
#      global: yes
#
#  - name: VirtualBox repo
#    get_url:
#      url: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
#      dest: /etc/yum.repos.d/
#
#  - name: Install required packages for VirtualBox
#    dnf:
#      name: "{{ packages }}"
#      state: present
#    vars:
#      packages:
#        - dkms
#        - kernel-devel
#        - make
#        - patch
#
#  - name: Install VirtualBox
#    dnf:
#      name: VirtualBox-6.1
#      state: present
#
#  - name: Install cowsay and fortune-mod
#    dnf:
#      name: "{{ packages }}"
#      state: present
#    vars:
#      packages:
#        - cowsay
#        - fortune-mod
#
#  - name: Install applications via Flatpak
#    community.general.flatpak:
#      name: "{{ apps }}"
#      state: present
#      remote: flathub
#    vars:
#      apps:
#        - com.spotify.Client
#        - org.signal.Signal
#        - org.telegram.desktop
#        - io.github.spacingbat3.webcord 
#        - com.discordapp.Discord
#        - net.xmind.XMind8
#        - org.keepassxc.KeePassXC
#        - com.getpostman.Postman
#        - io.github.mimbrero.WhatsAppDesktop
#        - com.slack.Slack
#        - org.ksnip.ksnip
#
#  - name: Import VSC key
#    rpm_key:
#      state: present
#      key: https://packages.microsoft.com/keys/microsoft.asc
#
#  - name: Create VSC repo
#    yum_repository:
#      name: code
#      description: Visual Studio Code
#      baseurl: https://packages.microsoft.com/yumrepos/vscode
#      gpgcheck: yes
#      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
#
#  - name: Install VSC
#    dnf:
#      name: code
#      state: present
#
#  - name: Install H.264 codec
#    dnf:
#      name: gstreamer1-plugin-openh264
#      state: present
#
#  - name: Create myfiles and vm directories
#    file:
#      path: "/mnt/{{ item }}"
#      state: directory
#    with_items: ["myfiles", "vm"]
#
#  - name: Mount LVs
#    ansible.posix.mount:
#      path: "/mnt/{{ item }}"
#      src: "/dev/files/{{ item }}"
#      fstype: ext4
#      state: mounted
#    with_items: ["myfiles", "vm"]
#   
#  - name: Create symbolic links
#    file:
#      src: "/mnt/myfiles/{{ item }}"
#      dest: "/home/jorge/{{ item }}"
#      force: true
#      state: link
#    with_items: ["123","Documents","Downloads","Dropbox","Pictures","Projects"]
#
#  - name: Set Java 11 as default
#    shell: alternatives --set java java-11-openjdk.x86_64
#
#  - name: Set Java JDK 11 as default
#    shell: alternatives --set javac java-11-openjdk.x86_64
