- name: Setup new fedora 31 machine
  hosts: all
  tasks:

  - name: Set hostname
    hostname:
      name: jalaptop.sevolutivo.ec

  - name: Update all packages
    dnf:
      name: '*'
      state: latest

  - name: Install RPM Fusion Free repository
    dnf:
      name: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-31.noarch.rpm
      state: present

  - name: Install RPM Fusion Non Free repository
    dnf:
      name: http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-31.noarch.rpm
      state: present

  - name: Install required packages
    dnf:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - digikam
        - gimp
        - sysstat
        - vlc
        - keepassx
        - java-1.8.0-openjdk-devel
        - lm_sensors
        - gnome-shell-extension-pomodoro
        - gnome-tweaks
        - xclip
        - chromium
        - podman-compose
        - nmap
        - httpie
        - powerline

  - name: Install Fedora Workstation repository
    dnf:
      name: fedora-workstation-repositories
      state: present
    
  - name: Enable Chrome repository
    shell: dnf config-manager --set-enabled google-chrome

  - name: Install Chrome
    dnf:
      name: google-chrome-stable
      state: present

  - name: Create Oracle Java 8 home dir
    file:
      path: /opt/java
      state: directory

  - name: Unpack Oracle Java 8
    unarchive:
      src: files/jdk-8u251-linux-x64.tar.gz
      dest: /opt/java
      owner: jorge
      group: jorge

  - name: Create SoapUI home dir
    file:
      path: /opt/soapui
      state: directory

  - name: Unpack SoapUI
    unarchive:
      src: files/SoapUI-5.5.0-linux-bin.tar.gz
      dest: /opt/soapui
      owner: jorge
      group: jorge
    
  - name: Create SoapUI symbolic link 
    file:
      src: "/opt/soapui/SoapUI-5.5.0/bin/soapui.sh"
      dest: "/usr/local/bin/soapui.sh"
      state: link
    
  - name: Import VSC key
    rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: Create VSC repo
    yum_repository:
      name: code
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgcheck: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: Install VSC
    dnf:
      name: code
      state: present

  - name: Active Powerline
    blockinfile:
      dest: /home/jorge/.bashrc
      block: |
        if [ -f `which powerline-daemon` ]; then
          powerline-daemon -q
          POWERLINE_BASH_CONTINUATION=1
          POWERLINE_BASH_SELECT=1
          . /usr/share/powerline/bash/powerline.sh
        fi
      backup: yes

  - name: Create Powerline config dir
    file:
      path: /home/jorge/.config/powerline
      state: directory
      owner: jorge
      group: jorge

  - name: Configure Git Powerline theme
    copy:
      dest: /home/jorge/.config/powerline/config.json
      owner: jorge
      group: jorge
      content: |
        {
            "ext": {
                "shell": {
                    "theme": "default_leftonly"
                }
            }
        }

  - name: Create SQL Developer home dir
    file:
      path: /opt/sqldeveloper
      state: directory

  - name: Unpack SQL Developer
    unarchive:
      src: files/sqldeveloper-19.2.1.247.2212-no-jre.zip
      dest: /opt/sqldeveloper
      owner: jorge
      group: jorge
    
  - name: Create SQL Developer script
    copy:
      dest: /usr/local/bin/sqldeveloper.sh
      owner: jorge
      group: jorge
      mode: u+x
      content: |
        #!/bin/bash
        cd /opt/sqldeveloper/sqldeveloper/
        ./sqldeveloper.sh

  - name: Install Node.js
    dnf:
      name: nodejs
      state: present

  - name: Install JHipster generator
    npm:
      name: generator-jhipster
      global: yes

  - name: Install yo
    npm:
      name: yo
      global: yes

  - name: Create IntelliJ home dir
    file:
      path: /opt/idea
      state: directory

  - name: Unpack IntelliJ
    unarchive:
      src: files/ideaIU-2020.1.tar.gz
      dest: /opt/idea
      owner: jorge
      group: jorge

  - name: Change setting in Sysctl for Inotify Watches Limit (required for IntelliJ)
    lineinfile:
      dest: /etc/sysctl.conf
      line: fs.inotify.max_user_watches = 524288

  - name: Apply Sysctl changes
    shell: sysctl -p --system
